<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\AppRoleController;
use App\Http\Controllers\Admin\AppUserController;
use App\Http\Controllers\Admin\TractorController;
use App\Http\Controllers\Admin\TrailerController;
use App\Http\Controllers\Admin\TripController;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Public welcome page
Route::get('/', function () {
    return view('welcome');
});

// Standard authenticated user dashboard
Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

// Authenticated user profile routes
Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});


// --- ADMIN SECTION ---
// All routes in this group are protected by the 'auth' and 'role:admin' middleware.
// They are prefixed with '/admin' and their names start with 'admin.'
Route::middleware(['auth', 'role:admin'])->prefix('admin')->name('admin.')->group(function () {

    // Admin Dashboard
    Route::get('/', function () {
        return view('admin.index');
    })->name('index');

    // Permissions CRUD Routes
    Route::resource('permissions', PermissionController::class);

    // Roles CRUD Routes
    Route::resource('roles', RoleController::class);

    // Users CRUD Routes
    Route::resource('users', UserController::class);

        Route::resource('app-roles', AppRoleController::class);
    Route::resource('app-users', AppUserController::class);

        Route::resource('tractors', TractorController::class);
    Route::resource('trailers', TrailerController::class);

    Route::post('stops/update-order', [TripController::class, 'updateStopOrder'])->name('stops.updateOrder');
    Route::resource('trips', TripController::class);

        Route::post('/trips/stops/order', [TripController::class, 'updateStopOrder'])->name('trips.stops.order');

    // AJAX endpoint for updating an existing Stop's location
    Route::post('/stops/{stop}/location', [TripController::class, 'updateStopLocation'])->name('stops.updateLocation');
});


// Include the authentication routes generated by Breeze
require __DIR__.'/auth.php';